// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'


    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkRuHkvQTB1MdAIyS2HMHKVYJ1zch3L2k',
    appId: '1:199947367416:web:60024ecf28582bf40b1c0d',
    messagingSenderId: '199947367416',
    projectId: 'todolistapp-ae459',
    authDomain: 'todolistapp-ae459.firebaseapp.com',
    storageBucket: 'todolistapp-ae459.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDV5cgFJl1OVcesWxbGhdyY3Y1nIfONcA',
    appId: '1:199947367416:android:8e008a00915bdf290b1c0d',
    messagingSenderId: '199947367416',
    projectId: 'todolistapp-ae459',
    storageBucket: 'todolistapp-ae459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNEWY-pTaVemfi79T_UPTJri1AMowknNU',
    appId: '1:199947367416:ios:1d47552bfb579a650b1c0d',
    messagingSenderId: '199947367416',
    projectId: 'todolistapp-ae459',
    storageBucket: 'todolistapp-ae459.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNEWY-pTaVemfi79T_UPTJri1AMowknNU',
    appId: '1:199947367416:ios:1d47552bfb579a650b1c0d',
    messagingSenderId: '199947367416',
    projectId: 'todolistapp-ae459',
    storageBucket: 'todolistapp-ae459.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkRuHkvQTB1MdAIyS2HMHKVYJ1zch3L2k',
    appId: '1:199947367416:web:0e51fbc95c957fb80b1c0d',
    messagingSenderId: '199947367416',
    projectId: 'todolistapp-ae459',
    authDomain: 'todolistapp-ae459.firebaseapp.com',
    storageBucket: 'todolistapp-ae459.appspot.com',
  );
}
